In [19]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'a': [10, 20, 30, 40, 50],
    'b': [5, 15, 25, 35, 45],
    'c': [-5, -15, -25, -35, -45],    
})

df

a   b   c
0  10   5  -5
1  20  15 -15
2  30  25 -25
3  40  35 -35
4  50  45 -45

In [20]:
from sklearn.preprocessing import MinMaxScaler

In [21]:
# Min-Max 정규화 (기본값은 0 ~ 1)
mms = MinMaxScaler(feature_range=(1, 3))
scaled_mms = mms.fit_transform(df)
scaled_mms

array([[1. , 1. , 3. ],
       [1.5, 1.5, 2.5],
       [2. , 2. , 2. ],
       [2.5, 2.5, 1.5],
       [3. , 3. , 1. ]])

In [22]:
col_mms = [item + '_m' for item in df.columns]
col_mms

['a_m', 'b_m', 'c_m']

In [23]:
df_mms = pd.DataFrame(scaled_mms, columns=col_mms)
df_mms

a_m  b_m  c_m
0  1.0  1.0  3.0
1  1.5  1.5  2.5
2  2.0  2.0  2.0
3  2.5  2.5  1.5
4  3.0  3.0  1.0

In [24]:
df_new = pd.concat([df, df_mms], axis=1)
df_new

a   b   c  a_m  b_m  c_m
0  10   5  -5  1.0  1.0  3.0
1  20  15 -15  1.5  1.5  2.5
2  30  25 -25  2.0  2.0  2.0
3  40  35 -35  2.5  2.5  1.5
4  50  45 -45  3.0  3.0  1.0

In [25]:
df_new = pd.DataFrame({
    'a': [1, 2, 3, 4, 5],
    'b': [1, 2, 3, 4, 5],
    'c': [1, 2, 3, 4, 5],    
})

df_new

a  b  c
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5

In [26]:
mms.fit_transform(df_new)

array([[1. , 1. , 1. ],
       [1.5, 1.5, 1.5],
       [2. , 2. , 2. ],
       [2.5, 2.5, 2.5],
       [3. , 3. , 3. ]])

In [27]:
mms.fit(df)
mms.transform(df)

array([[1. , 1. , 3. ],
       [1.5, 1.5, 2.5],
       [2. , 2. , 2. ],
       [2.5, 2.5, 1.5],
       [3. , 3. , 1. ]])

In [28]:
mms.transform(df_new)

array([[0.55, 0.8 , 3.3 ],
       [0.6 , 0.85, 3.35],
       [0.65, 0.9 , 3.4 ],
       [0.7 , 0.95, 3.45],
       [0.75, 1.  , 3.5 ]])

In [31]:
mms.min_ 

array([0.5 , 0.75, 3.25])